version: "3"
services:
  web:
    build:
      context: ./php
    ports:
      - "8111:8000"
    volumes:
      - '../:/app'
    depends_on:
      - redis
  redis:
    image: redis
    restart: always

